repos:
  - repo: local
    hooks:
      - id: pytest
        name: Run Pytest with Coverage
        entry: bash -c 'cd backend && python -m pytest'
        language: system
        types: [python]
        args: ["--cov", "--cov-report=term"]
        pass_filenames: false
