global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "docker-web-backend"
    static_configs:
      - targets: ["backend:5000"]
    metrics_path: "/metrics"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
